### ISSUE TITLE
章鱼妹的动态展示和契法的

### ISSUE THREAD

**Issue by sdjvhfb** [IrisuM/AntiKaniForAlchemyStars#1]
还是说动态立绘不能反和谐？
![image](https://github.com/IrisuM/AntiKaniForAlchemyStars/assets/136979455/a46acb62-215d-43ba-9901-184be4e6ede7)
![image](https://github.com/IrisuM/AntiKaniForAlchemyStars/assets/136979455/bacf20bb-98d2-48d7-a9a7-6e43041516a2)

**Comment by IrisuM** [comment]
已修复，可以更新git上的数据包再试试
