### ISSUE TITLE
覆盖文件之后打开游戏会黑屏

### ISSUE THREAD

**Issue by yuelemao** [IrisuM/AntiKaniForAlchemyStars#10]
我也跟隔壁帖子那位老哥一样会黑屏，不过我是尝试的3.12。打开游戏显示完图标之后，会在本来应该显示健康游戏那一段文字的地方黑屏，等很久也没能进去。我也尝试着复制粘贴了几次还是无法打开，如果恢复了原本的文件就又可以打开了。我在模拟器以及安卓手机上边都尝试了几次，得到的结果都是一样的，黑屏。
是因为国服资源号已经到了3.15而补丁只到3.12所以打不开吗？
十分感谢作者的辛苦制作，如果作者想出解决办法，或者觉得我的操作失误的话请在下方留言，万分感谢（^_^）
ps：超喜欢绯以及契法的，就为了这两个才来寻找补丁，国服对这两个角色的和谐简直是罪大恶极！

**Comment by sdjvhfb** [comment]
现在4.6还是黑屏
