### ISSUE TITLE
反和谐失效

### ISSUE THREAD

**Issue by 24kkkkkkk** [IrisuM/AntiKaniForAlchemyStars#3]
![Screenshot_2023-06-21-09-32-42-49_472f9a6bdce01044d5917451c8eac891](https://github.com/IrisuM/AntiKaniForAlchemyStars/assets/93512960/484183e4-dac2-493c-9e4f-fb0055a6a1bb)
替换文件后进游戏会提示更新

**Comment by FuyumiM** [comment]
可以看一下是否复制完全，是否有文件复制失败，rm有文件数参考
还有就是是否有使用最新的manifest
我这边本地测试是正常可以进入游戏的

**Comment by FuyumiM** [comment]
可以确认下abs文件总数是否是3934，理论上应该是这个数

**Comment by 24kkkkkkk** [comment]
![Screenshot_2023-06-21-10-37-32-73_9e8df3d0c7c1f50248b6ee043a653d26](https://github.com/IrisuM/AntiKaniForAlchemyStars/assets/93512960/e7d2968b-180e-4c94-81c3-992050db8ce7)
替换后的文件应该没问题，但进游戏就提示更新，manifest用的是包里的

**Comment by FuyumiM** [comment]
> ![Screenshot_2023-06-21-10-37-32-73_9e8df3d0c7c1f50248b6ee043a653d26](https://user-images.githubusercontent.com/93512960/247382325-e7d2968b-180e-4c94-81c3-992050db8ce7.jpg) 替换后的文件应该没问题，但进游戏就提示更新，manifest用的是包里的

你这个是云盘里下载的吧，可以看一下云盘的rm，云盘资源包替换后还需要替换最新的manifest，也就是适配当前1.7版本的这个

**Comment by FuyumiM** [comment]
云盘方便下载，但是管理文件不好管理，我就除了那个很少更新的资源包外，还单独传了一个manifest文件

**Comment by 24kkkkkkk** [comment]
替换完以后能进了，谢谢大佬
![139e325ef49bdb74](https://github.com/IrisuM/AntiKaniForAlchemyStars/assets/93512960/38efab19-b556-46a9-9e64-bc4f57bf0ea0)

**Comment by FuyumiM** [comment]
> 替换完以后能进了，谢谢大佬 ![139e325ef49bdb74](https://user-images.githubusercontent.com/93512960/247387246-38efab19-b556-46a9-9e64-bc4f57bf0ea0.jpg)

OK，那我关闭了
