### ISSUE TITLE
艾米和奥菲娜反和谐失败

### ISSUE THREAD

**Issue by cxk1998** [IrisuM/AntiKaniForAlchemyStars#4]

**Comment by 24kkkkkkk** [comment]
收到，请等待后续修复

**Comment by 24kkkkkkk** [comment]
![Screenshot_2023-06-27-20-17-32-93_472f9a6bdce01044d5917451c8eac891](https://github.com/IrisuM/AntiKaniForAlchemyStars/assets/93512960/40b2be4b-27e9-4cf6-81f1-3ea61ec16ff1)
![Screenshot_2023-06-27-20-17-44-53_472f9a6bdce01044d5917451c8eac891](https://github.com/IrisuM/AntiKaniForAlchemyStars/assets/93512960/8fa855f7-bc2e-4ce1-a4d9-d3393419516c)
已修复，若出现白屏请重新替换out
