### ISSUE TITLE
是不是失效了

### ISSUE THREAD

**Issue by sdjvhfb** [IrisuM/AntiKaniForAlchemyStars#5]
abs文件：
![image](https://github.com/IrisuM/AntiKaniForAlchemyStars/assets/136979455/6f6ebfb4-aab5-446b-b964-1f5d09f89c94)
一进游戏就强制更新了：
![image](https://github.com/IrisuM/AntiKaniForAlchemyStars/assets/136979455/f07d5b1c-93b2-4b8f-a7e2-677caa470944)

**Comment by sdjvhfb** [comment]
才发现更新资源号了
![image](https://github.com/IrisuM/AntiKaniForAlchemyStars/assets/136979455/5d20eb6b-1f8b-4056-8688-feb149319271)

**Comment by IrisuM** [comment]
放假在外面玩呢，回家更新

**Comment by sdjvhfb** [comment]
辛苦大佬了

**Comment by 24kkkkkkk** [comment]
已更新，out包里的manifest就是最新的

**Comment by Mo-Ling** [comment]
大佬，1.8好像还有几个是和谐版的，贡露原皮和火天使觉醒等等

**Comment by sdjvhfb** [comment]
![image](https://github.com/IrisuM/AntiKaniForAlchemyStars/assets/136979455/0d15b0d6-68af-427f-858f-1227d80832c0)
红与黑好像出问题了

**Comment by 24kkkkkkk** [comment]
🤔什么情况下出现的，重启游戏问题依然存在吗

**Comment by 24kkkkkkk** [comment]
> 大佬，1.8好像还有几个是和谐版的，贡露原皮和火天使觉醒等等

收到，请等待后续更新

**Comment by Mo-Ling** [comment]
![Uploading Screenshot_20230624_231730_com.tencent.baiye.jpg…]()
我这边红黑没问题

**Comment by Mo-Ling** [comment]
![Screenshot_20230624_231730_com tencent baiye](https://github.com/IrisuM/AntiKaniForAlchemyStars/assets/136995102/5e74592f-9625-4528-8cb0-9a1af5577206)
我这边红黑没问题

**Comment by 24kkkkkkk** [comment]
同
![Uploading Screenshot_2023-06-24-23-15-43-44_472f9a6bdce01044d5917451c8eac891.jpg…]()

**Comment by sdjvhfb** [comment]
![image](https://github.com/IrisuM/AntiKaniForAlchemyStars/assets/136979455/b69a992c-5ed5-4f9a-a9a0-8a706c4d9790)
是光灵界面出问题，但点进去又是正常的，重启也没用
![image](https://github.com/IrisuM/AntiKaniForAlchemyStars/assets/136979455/4225ea4c-acaa-45c0-a0a2-6fb31e437fd7)

**Comment by FuyumiM** [comment]
> ![image](https://user-images.githubusercontent.com/136979455/248523567-b69a992c-5ed5-4f9a-a9a0-8a706c4d9790.png) 是光灵界面出问题，但点进去又是正常的，重启也没用 ![image](https://user-images.githubusercontent.com/136979455/248523582-4225ea4c-acaa-45c0-a0a2-6fb31e437fd7.png)

可能是这个资源包复制失败了，没找到这个材质，试试重复覆盖一下？

**Comment by sdjvhfb** [comment]
不行，还是和原来一样

**Comment by 24kkkkkkk** [comment]
> 大佬，1.8好像还有几个是和谐版的，贡露原皮和火天使觉醒等等

已修复，请替换最新的manifest

**Comment by cody1991** [comment]
今天一直提示更新失败哎

**Comment by 24kkkkkkk** [comment]
我这里也是偶尔有连接失败的情况，退出重进一下就好了

**Comment by 24kkkkkkk** [comment]
> 今天一直提示更新失败哎

我这里也是偶尔有连接失败的情况，退出重进一下就好了

**Comment by cody1991** [comment]
> > 今天一直提示更新失败哎
> 
> 我这里也是偶尔有连接失败的情况，退出重进一下就好了

退出重试好多次了，还是不行，我重新下载试试

**Comment by cody1991** [comment]
重新下载安装倒是可以了。不过鸡丁和红与黑有问题～没封面图

**Comment by Mo-Ling** [comment]
大佬，网盘里的压缩包是最新的吗，复制完打开游戏会提示下载278m的东西，然后下到一半会卡住

**Comment by 24kkkkkkk** [comment]
> 大佬，网盘里的压缩包是最新的吗，复制完打开游戏会提示下载278m的东西，然后下到一半会卡住

网盘里的没更新，git里是最新的
